### ISSUE TITLE
Question, pro/con of not just using the switch SENS with and ADC?

### ISSUE THREAD

**Issue by ptr727** [beast-devices/TougherPowerMonitor-HW#2]
Given the switch has a sense output for current and temp monitoring, what are your thoughts on not just using e.g. multiple 2-channel TPS2HB08-Q1 and an onboard or I2C ADC?

**Comment by ahillbom** [comment]
Your proposal is indeed a valid solution. 

The main reason for not going in the direction you propose is not good enough current sense accuracy of the TPS2HB08-Q1.

![image](https://user-images.githubusercontent.com/8793368/148125852-1f0de514-5bb8-467d-9990-43a49947d222.png)

**Comment by ptr727** [comment]
I noticed from the accuracy graph on the notes that at low currents accuracy is very poor.
Yet, adding two load sense resistors is also not great.
I'm thinking one could choose the switch with sense and sacrifice accuracy, or use the sensor with a very low R switching FET?

I'm looking at a switching solution for a project like this: https://github.com/computergeek1507/PB_16/issues/2

**Comment by ahillbom** [comment]
The primary purpose of this project is to measure the voltage and current with a reasonable accuracy. Typically, the current measurement using the FET resistance is good enough for ballpark measurements only. It is usually good enough for implementing current limiting, for example.
